services:
  postgres:
    image: postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock-system
    ports:
      - "5423:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
  db-test:
    image: postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock-system-test
    ports:
      - "5424:5432"
    volumes:
      - db-test:/var/lib/postgresql/18/docker

volumes:
  postgres_data:
  db-test: